# IndexIQ — Sponsorship & Funding
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Mamun]
ko_fi: indexiq
open_collective: indexiq
custom:
  - https://buymeacoffee.com/indexiq
  - https://opencollective.com/indexiq
